spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shopnew0304
    username: sa
    password:
    driver-class-name: org.h2.Driver
  #jpa
      # 1. show_sql -> system.out 출력
      # 2. format_sql -> logger에서 출력
    #show_sql: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
# Hibernate SQL ?? -> DEBUG
logging:
  level:
    org.hibernate.SQL: debug
    #org.hibernate.orm.jdbc.bind: trace
    #org.hibernate.type: trace